### ISSUE TITLE
windows10系统 idea终端执行mvn命令报错问题

### ISSUE THREAD

**Issue by LoganZhuZzz** [hcsp/run-a-mvn-command#3]
windows10系统 idea的mvn插件执行mvn命令正常执行 终端命令行执行mvn compile报错问题
信息如下:
'''
D:\hcsp\debug\run-a-mvn-command>mvn compile
[INFO] Scanning for projects...
[INFO]
[INFO] -----------------------< hcsp:run-a-mvn-command >-----------------------
[INFO] Building run-a-mvn-command 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[WARNING] The POM for com.github.hcsp:test-plugin:jar:1.0-SNAPSHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.271 s
[INFO] Finished at: 2021-01-13T10:53:22+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Plugin com.github.hcsp:test-plugin:1.0-SNAPSHOT or one of its dependencies could not be resolved: Failure to find com.github.hcsp:test-plugin:jar:1.0-SNAPSHOT in https://maven.
aliyun.com/repository/public was cached in the local repository, resolution will not be reattempted until the update interval of aliyunmaven has elapsed or updates are forced -> [Help
1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginResolutionException
'''
@blindpirate  请问是阿里云镜像配置问题么 为什么idea自带的MAVEN工具执行任何命令都没问题 终端执行会失败

**Comment by blindpirate** [comment]
@zeq96 是你的全局阿里云镜像配置问题。多半是你的全局settings.xml里的`<mirrorOf>`配置用了星号，强制镜像掉了所有的仓库，包括项目配置的本地仓库。
